[package]
name = "gerax-auth"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Autenticação"

[dependencies]
gerax-core.workspace = true
gerax-http.workspace = true

serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true
serde_json.workspace = true

jsonwebtoken = { workspace = true, features = ["use_pem"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
