[package]
name = "gerax-http"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Abstrações HTTP do framework Gerax"

keywords = [
    "http",
    "web",
    "framework",
]

categories = [
    "web-programming"
]

[dependencies]
gerax-core.workspace = true
gerax-config.workspace = true
gerax-macros.workspace = true

async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
urlencoding.workspace = true
matchit.workspace = true
http.workspace = true
bytes.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full"] }