name: app_mongo

services:
  mongo:
    image: docker.io/library/mongo:7-jammy
    container_name: app_mongo
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - $MONGO_PORT:$MONGO_PORT

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
