[package]
name = "gerax"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Framework Gerax"

[dependencies]
gerax-core.workspace = true
gerax-macros.workspace = true

gerax-http = { workspace = true, optional = true }

gerax-actix = { workspace = true, optional = true }
gerax-axum = { workspace = true, optional = true }
gerax-poem = { workspace = true, optional = true }
gerax-salvo = { workspace = true, optional = true }

gerax-mongodb = { workspace = true, optional = true }
gerax-postgres = { workspace = true, optional = true }
gerax-turso = { workspace = true, optional = true }

gerax-ai = { workspace = true, optional = true }

gerax-mysql = { workspace = true, optional = true }

gerax-auth = { workspace = true, optional = true }
gerax-config = { workspace = true, optional = true }

gerax-capnp = { workspace = true, optional = true }
gerax-websocket = { workspace = true, optional = true }
gerax-openapi = { workspace = true, optional = true }

[features]
default = ["actix", "mongodb"]

actix = ["dep:gerax-http", "dep:gerax-actix"]
axum = ["dep:gerax-http", "dep:gerax-axum"]
poem = ["dep:gerax-http", "dep:gerax-poem"]

mongodb = ["dep:gerax-mongodb"]
postgres = ["dep:gerax-postgres"]
turso = ["dep:gerax-turso"]

ai = ["dep:gerax-ai"]

mysql = ["dep:gerax-mysql"]

auth = ["dep:gerax-auth"]
config = ["dep:gerax-config"]

capnp = ["dep:gerax-capnp"]
websocket = ["dep:gerax-websocket"]
openapi = ["dep:gerax-openapi"]