pub mod config;
pub mod error;
pub mod extractor;
pub mod jwt;
pub mod middleware;
pub mod refresh;
pub mod routes;
pub mod scope_authorizer;
pub mod traits;
pub mod types;

pub use config::{AlgorithmConfig, AuthConfig, ConfiguredAuthState};
pub use extractor::AuthenticatedUser;
pub use jwt::{Algorithm, JwtAuthenticator};
pub use middleware::AuthMiddleware;
pub use refresh::{MemoryTokenStorage, RefreshTokenStore, RotationPolicy, TokenStorage};
pub use routes::{login, refresh, AuthState};
pub use scope_authorizer::ScopeAuthorizer;
pub use traits::{Authenticator, Authorizer, AuthError, AuthResult};
pub use types::{Claims, RefreshToken, TokenPair};
