[package]
name = "gerax-es"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Event Sourcing para o Gerax"

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
thiserror.workspace = true

# Optional adapters
sqlx = { workspace = true, features = ["chrono"], optional = true }
mongodb = { workspace = true, optional = true }
bson = { workspace = true, optional = true }
futures = { workspace = true, optional = true }

[dev-dependencies]
tokio.workspace = true

[features]
default = []
postgres = ["dep:sqlx"]
mongodb = ["dep:mongodb", "dep:bson", "dep:futures"]