[package]
name = "gerax-grpc"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Suporte a gRPC no Gerax"

[dependencies]
gerax-core.workspace = true
gerax-http.workspace = true
gerax-db.workspace = true
gerax-codec.workspace = true
gerax-config.workspace = true
gerax-rpc.workspace = true
gerax-macros.workspace = true

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tonic.workspace = true
tonic-prost = "0.14"
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
tonic-build.workspace = true
tonic-prost-build = "0.14"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

