[package]
name = "gerax-graphql"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Suporte a GraphQL no Gerax"

[dependencies]
gerax-core.workspace = true
gerax-http.workspace = true
gerax-db.workspace = true

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
futures.workspace = true

async-graphql = { workspace = true }

gerax-websocket.workspace = true
tokio.workspace = true
sha2.workspace = true
hex.workspace = true
