[package]
name = "gerax-postgres"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Suporte ao PostgreSQL"

[dependencies]
gerax-core.workspace = true

tokio-postgres.workspace = true
serde.workspace = true
futures.workspace = true
