[package]
name = "gerax-postgres"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Suporte ao PostgreSQL"

[dependencies]
gerax-core.workspace = true
gerax-config.workspace = true
gerax-db.workspace = true

tokio-postgres = { workspace = true }
postgres-native-tls = "0.5"
native-tls = "0.2"
tokio-postgres-rustls = { version = "0.14", default-features = false, features = ["webpki-roots"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
webpki-roots = "1.0"
serde.workspace = true
serde_json.workspace = true

async-trait.workspace = true
thiserror.workspace = true
dotenv.workspace = true
tokio = { version = "1", features = ["full"] }
