[package]
name = "gerax-postgres"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

description = "Suporte ao PostgreSQL"

[dependencies]
gerax-core.workspace = true
gerax-config.workspace = true
gerax-db.workspace = true

sqlx = { workspace = true }

serde.workspace = true
serde_json.workspace = true

async-trait.workspace = true
thiserror.workspace = true
dotenv.workspace = true
tokio = { version = "1", features = ["full"] }
